# Generated by Django 3.0 on 2019-12-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0003_pokemon_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='legend',
            new_name='legendary',
        ),
    ]
